### ISSUE TITLE
Migrate ownership to NWT

### ISSUE THREAD

**Issue by wwieder** [NWTlter/NWT_CLM#23]
@scelmendorf can you help us migrate ownership of this repo to LTER?

**Comment by scelmendorf** [comment]
Sure. I think (?) Hannah has permissions to create repositories in NWTlter and therefore should be able to transfer the repository. Did you try that?

**Comment by hhollandmoritz** [comment]
No, I haven't. Sarah, what's the best way to transfer ownership of a
repository? I've tried to do it in the past for the Fierer lab and made a
mess of things. Should a simply create a new repository (that would erase
all the history we've built) or is there a more elegant solution?

Thanks!
Hannah

--
Hannah Holland-Moritz
Doctoral Candidate, Fierer Lab
EBIO Department
University of Colorado Boulder
she/her pronouns
hhollandmoritz@gmail.com
https://hhollandmoritz.github.io

I may email you outside your working hours. Please don't feel pressure to
respond until your working hours.
<https://secure-web.cisco.com/1nTIVc1yBgvWcr9ZPOBTASp9_B57lnQ2aj5sai1lo304Yz6TAYV1KgaIjy8mdd6ecxxkAuyveefGtuo9q-x_tPBIQou65oUF1ejWVINiDhLx1aoll_9TM-3YMx6GtsWx931K0aQIW1RC6R_C-kG7snK823Jq9eiPb_UJMfiq2WSEql7gVYJNpN1upiP5-BM5X7eR0rXGhQm_s0F9dbvfiNpTzXlIaFX3s2MqXFP7TXHpdPziIhb4_M4GWqaqWzSfmqV7CqeEEr5ure6eRjV6oVFqKBRHTIZV_5CotcOyf0zbbnoyPuJ3KAOyJ_gdGqLWoH1BtS5Ezvhvp13K32T-sfpYcBee6pJcdFI7RtfL3223-lSBJswahOQtYVgKxyhyRAN8rUw3FckK6se-HGVppDOI0jBaWAj92AQgUJgsGIO9fgK8vOJk0BMY8_65FW55B2rnNMrPH41SUusHSZvOPzw/https%3A%2F%2Fgotguts.org>

**Comment by scelmendorf** [comment]
I think you should be able to transfer it directly, see here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository
Admittedly I don't know that I have transferred something from a personal to an organizational repository before, but a collaborator of mine just did and it seemed to go fine - i.e. the issues and history and stuff all moved. What happened with the fierer lab one and did you transfer or move otherwise?

**Comment by scelmendorf** [comment]
Plan B - you could just make a fake repo with one commit and one issue and transfer it, and then we delete it, to figure out how it works. Sometimes I find trying by doing easier than trying by following the directions.

**Comment by hhollandmoritz** [comment]
Great idea! I'll try it with a dummy repo first and then try it on the real
thing. This week is turning into a bit of a crazy one though, so I won't
get to it until Friday at the earliest.

--
Hannah Holland-Moritz
Doctoral Candidate, Fierer Lab
EBIO Department
University of Colorado Boulder
she/her pronouns
hhollandmoritz@gmail.com
https://hhollandmoritz.github.io

I may email you outside your working hours. Please don't feel pressure to
respond until your working hours.
<https://secure-web.cisco.com/1nTIVc1yBgvWcr9ZPOBTASp9_B57lnQ2aj5sai1lo304Yz6TAYV1KgaIjy8mdd6ecxxkAuyveefGtuo9q-x_tPBIQou65oUF1ejWVINiDhLx1aoll_9TM-3YMx6GtsWx931K0aQIW1RC6R_C-kG7snK823Jq9eiPb_UJMfiq2WSEql7gVYJNpN1upiP5-BM5X7eR0rXGhQm_s0F9dbvfiNpTzXlIaFX3s2MqXFP7TXHpdPziIhb4_M4GWqaqWzSfmqV7CqeEEr5ure6eRjV6oVFqKBRHTIZV_5CotcOyf0zbbnoyPuJ3KAOyJ_gdGqLWoH1BtS5Ezvhvp13K32T-sfpYcBee6pJcdFI7RtfL3223-lSBJswahOQtYVgKxyhyRAN8rUw3FckK6se-HGVppDOI0jBaWAj92AQgUJgsGIO9fgK8vOJk0BMY8_65FW55B2rnNMrPH41SUusHSZvOPzw/https%3A%2F%2Fgotguts.org>

**Comment by scelmendorf** [comment]
Ok - super! I think (?) though can't quite recall how the default organization permissions work that you will have permissions to add a repository but possibly not to delete one from the NWT organization unless you are an admin (though maybe if you create it you default to local admin of that repository?). Anyhow, if you find you have created something that you cannot delete in NWTlter organization, lmk and I can remove it. Definitely name your fake repo something that is NOT the same as the real one you will be transfering bc there are rules against transfering things if that name already exists. Timeline fine for me - thank you in advance for doing all this!

**Comment by hhollandmoritz** [comment]
Great! I'll probably name it something obvious like transfer_repo_test.

--
Hannah Holland-Moritz
Doctoral Candidate, Fierer Lab
EBIO Department
University of Colorado Boulder
she/her pronouns
hhollandmoritz@gmail.com
https://hhollandmoritz.github.io

I may email you outside your working hours. Please don't feel pressure to
respond until your working hours.
<https://secure-web.cisco.com/1nTIVc1yBgvWcr9ZPOBTASp9_B57lnQ2aj5sai1lo304Yz6TAYV1KgaIjy8mdd6ecxxkAuyveefGtuo9q-x_tPBIQou65oUF1ejWVINiDhLx1aoll_9TM-3YMx6GtsWx931K0aQIW1RC6R_C-kG7snK823Jq9eiPb_UJMfiq2WSEql7gVYJNpN1upiP5-BM5X7eR0rXGhQm_s0F9dbvfiNpTzXlIaFX3s2MqXFP7TXHpdPziIhb4_M4GWqaqWzSfmqV7CqeEEr5ure6eRjV6oVFqKBRHTIZV_5CotcOyf0zbbnoyPuJ3KAOyJ_gdGqLWoH1BtS5Ezvhvp13K32T-sfpYcBee6pJcdFI7RtfL3223-lSBJswahOQtYVgKxyhyRAN8rUw3FckK6se-HGVppDOI0jBaWAj92AQgUJgsGIO9fgK8vOJk0BMY8_65FW55B2rnNMrPH41SUusHSZvOPzw/https%3A%2F%2Fgotguts.org>

**Comment by hhollandmoritz** [comment]
Transfer is complete, but I think Will and I no longer have the power to approve pull requests. So it would be nice to have that power back. :) Also, I can't delete the test repo that I created. It's called NWTlter/transfer_repo_test
