### ISSUE TITLE
relative humidity always 100%

### ISSUE THREAD

**Issue by wwieder** [NWTlter/NWT_CLM#30]
The latest simulations I've been doing with CLM have really high GPP. I also noticed that relative humidity on the input data is always 100%.  It looks like the data being read into `prepare_forcings_for_clm.R` have rH > 100%, plot below
![image](https://user-images.githubusercontent.com/8031012/140657866-b822778f-c900-442a-add8-646967b9fb4c.png)

These input data (generated 2021-03-02) came from files for E and W towers `*_flux_P_reddyproc_cleaned.txt`  
I'm wondering if this issue was generated with this code block
 https://github.com/NWTlter/NWT_CLM/blob/d9300fce8f1941a072b7c7eb7527272ca99626f3/clean_tvan_data.R#L454

which came in with this commit in Nov 2020
https://github.com/NWTlter/NWT_CLM/commit/c3ee346faa0b755e15e2b3ad8a2f61aebc6c9f48

I think the rH values may already be in %, so the values here are 100x larger than they should be.

**Comment by katyarjay** [comment]
The rH values were already converted to % in the tvan_L1_preprocess.R script, so the values ended up being 100x too large when multiplied by 100 again in the clean_tvan_data.R script. These lines will be removed from the clean_tvan_data.R script.

**Comment by wwieder** [comment]
closed by #33
